from langchain.prompts import PromptTemplate

multi_context_prompt = PromptTemplate(
    input_variables=["schema_context", "logging_context", "question"],
    template=(
        "You have two separate pieces of context:\n\n"
        "=== SCHEMA CONTEXT (Main DB) ===\n"
        "{schema_context}\n\n"
        "=== LOGGING CONTEXT (queries_log & generated_views) ===\n"
        "{logging_context}\n\n"
        "You must produce **FOUR** outputs, each in a **separate code block**, labeled exactly:\n\n"
        "1) -- Final Query\n"
        "```sql\n"
        "<YOUR SELECT STATEMENT HERE>\n"
        "```\n\n"
        "2) -- Insert into queries_log\n"
        "```sql\n"
        "<YOUR INSERT INTO queries_log STATEMENT HERE>\n"
        "```\n\n"
        "3) -- Create or replace view\n"
        "```sql\n"
        "<YOUR CREATE OR REPLACE VIEW STATEMENT HERE>\n"
        "```\n\n"
        "4) -- Insert into generated_views\n"
        "```sql\n"
        "<YOUR INSERT INTO generated_views STATEMENT HERE>\n"
        "```\n\n"
        "Important Requirements:\n"
        "1. Each SQL statement **must only reference columns and tables** that actually exist in the schema context.\n"
        "   - If the question asks for columns not in the schema context, handle gracefully (e.g., note they do not exist).\n"
        "   - Do not invent columns or tables that are not listed.\n"
        "2. The Final Query must answer the user's question using valid columns from the schema.\n"
        "3. The Insert into queries_log must contain:\n"
        "    - question = the exact user question\n"
        "    - description = a short description (NOT NULL)\n"
        "    - sql_text = the exact same SQL query from the 'Final Query' block\n"
        "    - created_at = use NOW() or CURRENT_TIMESTAMP\n"
        "   (Do NOT output NULL for description or sql_text.)\n"
        "4. The Create or replace view statement must match the Final Query's SELECT.\n"
        "5. The Insert into generated_views references the new view.\n"
        "6. If query_id or view_id are serial/auto-increment, you can omit them or use DEFAULT, etc.\n"
        "7. Strictly follow the four labeled code blocks, with no extra commentary or text outside them.\n"
        "8. Make sure that the spelling of columns and tables are right. Do not invent names, make sure to get everything from the SCHEMA CONTEXT ABOVE.\n\n"
        "9. Make sure not to mismatch a column and a table. Always check in the SCHEMA CONTEXT above that a columns is rightly entitled to a table.\n\n"
        "The question is:\n"
        '"{question}"\n\n'
        "Now produce the four code blocks in the exact order and format shown above. "
        "Remember: only valid columns/tables that exist in the schema context.\n"
    ),
)
